### ISSUE TITLE
[FEAT] Allow neon_speech to run offline

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/neon-diana-utils#69]
### Objective

Currently, the neon_speech container will not run without an internet connection. All of the other services load without one, but since neon_speech pulls down a model from HuggingFace on init, the container consistently fails.

### Initial Implementation Requirements

Most likely path forward is either to build an image with the model baked in (seems pretty large) or to set the cache directory as a PVC, allowing you to run offline as long as you are online long enough to get the model into a persistent cache.

**Comment by mikejgray** [comment]
[Looks like the default cache directory](https://github.com/huggingface/huggingface_hub/blob/3788f537b10c7d02149d6bf017d2ce19885f90a2/src/huggingface_hub/constants.py#L112) is ~/.cache/huggingface/hub

**Comment by NeonDaniel** [comment]
The neon_speech-defailt_model image should work here, though I believe it's only English for the moment
